<a href="https://colab.research.google.com/github/shikhharsiingh/Tensorflow-ML-Basics/blob/main/Tensorflow_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import numpy as np
import tensorflow_probability as tfp

In [ ]:
mutable = tf.Variable([10,4])
immutable = tf.constant([4,5])
print(mutable)
mutable[0].assign(5)
print(mutable)
#immutable[0].assign(6)
print(immutable)

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  4], dtype=int32)>
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([5, 4], dtype=int32)>
tf.Tensor([4 5], shape=(2,), dtype=int32)


In [ ]:
rand = tf.random.Generator.from_seed(42)
rand = rand.normal(shape = (2,3))         
rand                                    #Random comes from normal distribution

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026],
       [-1.2573844 , -0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
a = tf.Variable([[1, 2],
                [3, 4],
                [5, 6]])
print(a)
#a = tf.random.shuffle(a)
#print(a)

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>


In [ ]:
tf.random.set_seed(42)
a = tf.random.shuffle(a)
a

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6],
       [1, 2]], dtype=int32)>

In [ ]:
npa = np.arange(1,25)
npa

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [ ]:
a = tf.constant(npa)
a

<tf.Tensor: shape=(24,), dtype=int64, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])>

In [ ]:
tens4 = tf.ones((2,3,4,5))
print(tens4.shape)
print(tens4.shape[-1])
print(tens4.ndim)
tf.size(tens4).numpy()

(2, 3, 4, 5)
5
4


120

In [ ]:
E = np.arange(1,100)
E = tf.Variable(E)
E

<tf.Variable 'Variable:0' shape=(99,) dtype=int64, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])>

In [ ]:
tf.reduce_max(E), tf.reduce_min(E)

(<tf.Tensor: shape=(), dtype=int64, numpy=99>,
 <tf.Tensor: shape=(), dtype=int64, numpy=1>)

In [ ]:
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=816>

In [ ]:
tf.math.reduce_std(tf.cast(E, dtype = tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=28.577381>

In [ ]:
tf.math.reduce_variance(tf.cast(E, dtype = tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=816.6667>

In [ ]:
indices = [1,2,3,4]

one_hot = tf.one_hot(indices, len(indices))
one_hot

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]], dtype=float32)>

In [ ]:
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
tf.math.sqrt(tf.cast(H, dtype = tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [ ]:
tf.math.log(tf.cast(H, dtype = tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [ ]:
J = tf.constant([1,2,3])
J.numpy()

array([1, 2, 3], dtype=int32)

Challenge

In [ ]:
A = tf.constant([1,2,3,4])
B = tf.constant([1,2,3,4], shape = [2,2])
C = tf.constant([1,2,3,4,5,6,7,8,9], shape = [3,3])
A,B,C

(<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], dtype=int32)>)

In [ ]:
A.shape, A.ndim, tf.size(A)

(TensorShape([4]), 1, <tf.Tensor: shape=(), dtype=int32, numpy=4>)

In [ ]:
K = tf.random.uniform([1,224,244,30])

In [ ]:
K = tf.squeeze(K)
K.shape

TensorShape([224, 244, 30])

In [ ]:
K = tf.range(1,11)
K.shape,tf.argmax(K)

(TensorShape([10]), <tf.Tensor: shape=(), dtype=int64, numpy=9>)

In [ ]:
def plot_decision_boundary(X, y, model):
  x_min, x_max = X[ :0].min() - 0.1 + X[:, 0].max() + 0.1
  y_min, y_max = X[ :1].min() - 0.1 + X[:, 1].max() + 0.1

  xx, yy = np.meshgrid(np.linspace(x_min, x_max, 100), np.linspace(y_min, y_max, 100))

  x_in = np.c[xx.ravel(), yy.ravel()]

  y_pred = model.predict(x_in)

  if len(y_pred[0]) > 1 :
    print("Doing multiclass classification")

    y_pred = np.argmax(y_pred, axis = 1).reshape(xx.shape)
  else:
    print("Doing binary classification")
    y_pred = np.round(y_pred).reshape(xx.shape)


  plt.contourf(xx, yy, y_pred, cmap = plt.cm.RdYlBu, alpha = 0.7)
  plt.scatter(X[:, 0], X[:, 1], c = y, s = 40, cmap = plt.cm.RdYlBu)
  plt.xlim(xx.min(), xx.max())
  plt.ylim(yy.min(), yy.max())

In [ ]:
plot_decision_boundary(model = model, x = x, y = y)

NameError: ignored